; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=mips64el-ps2-elf -O1 --disable-machine-licm -mcpu=r5900 -verify-machineinstrs < %s | \
; RUN:   FileCheck %s -check-prefix=R5900

define float @FMin(float %a, float %b) {
; R5900-LABEL: FMin:
; R5900:       # %bb.0:
; R5900-NEXT:    jr $ra
; R5900-NEXT:    min.s $f0, $f12, $f13
  %1 = call float @llvm.minnum.f32(float %a, float %b)
  ret float %1
}

define float @FMax(float %a, float %b) {
; R5900-LABEL: FMax:
; R5900:       # %bb.0:
; R5900-NEXT:    jr $ra
; R5900-NEXT:    max.s $f0, $f12, $f13
  %1 = call float @llvm.maxnum.f32(float %a, float %b)
  ret float %1
}

define float @Sqrt(float %a) {
; R5900-LABEL: Sqrt:
; R5900:       # %bb.0:
; R5900-NEXT:    jr $ra
; R5900-NEXT:    sqrt.s $f0, $f12
  %1 = call float @llvm.sqrt.f32(float %a)
  ret float %1
}

define float @RSqrt(float %a, float %b) {
; R5900-LABEL: RSqrt:
; R5900:       # %bb.0:
; R5900-NEXT:    jr $ra
; R5900-NEXT:    rsqrt.s $f0, $f12, $f13
  %1 = call float @llvm.sqrt.f32(float %b)
  %2 = fdiv float %a, %1
  ret float %2
}
