; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=mips64el-ps2-elf -O1 --disable-machine-licm -mcpu=r5900 -verify-machineinstrs < %s | \
; RUN:   FileCheck %s -check-prefix=R5900

define float @MAdd1(float %a, float %b, float %c, float %d) {
; R5900-LABEL: MAdd1:
; R5900:       # %bb.0:
; R5900-NEXT:    adda.s $f12, $f13
; R5900-NEXT:    jr $ra
; R5900-NEXT:    madd.s $f0, $f14, $f15
  %1 = fadd float %a, %b
  %2 = fmul float %c, %d
  %3 = fadd float %1, %2
  ret float %3
}

define float @MAdd2(float %a, float %b, float %c, float %d) {
; R5900-LABEL: MAdd2:
; R5900:       # %bb.0:
; R5900-NEXT:    suba.s $f12, $f13
; R5900-NEXT:    jr $ra
; R5900-NEXT:    msub.s $f0, $f14, $f15
  %1 = fsub float %a, %b
  %2 = fmul float %c, %d
  %3 = fsub float %1, %2
  ret float %3
}

define float @MAdd3(float %a, float %b, float %c, float %d, float %e, float %f) {
; R5900-LABEL: MAdd3:
; R5900:       # %bb.0:
; R5900-NEXT:    mula.s $f12, $f13
; R5900-NEXT:    msuba.s $f14, $f15
; R5900-NEXT:    jr $ra
; R5900-NEXT:    madd.s $f0, $f16, $f17
  %1 = fmul float %a, %b
  %2 = fmul float %c, %d
  %3 = fsub float %1, %2
  %4 = fmul float %e, %f
  %5 = fadd float %4, %3
  ret float %5
}
