; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=mips64el-ps2-elf -O0 --disable-machine-licm -mcpu=r5900 -verify-machineinstrs < %s | \
; RUN:   FileCheck %s -check-prefix=R5900O0
; RUN: llc -mtriple=mips64el-ps2-elf -O1 --disable-machine-licm -mcpu=r5900 -verify-machineinstrs < %s | \
; RUN:   FileCheck %s -check-prefix=R5900O1
; RUN: llc -mtriple=mips64el-ps2-elf -O2 --disable-machine-licm -mcpu=r5900 -verify-machineinstrs < %s | \
; RUN:   FileCheck %s -check-prefix=R5900O2

define i32 @Mul32(i32 signext %a, i32 signext %b) nounwind {
; R5900O0-LABEL: Mul32:
; R5900O0:       # %bb.0:
; R5900O0-NEXT:    move $2, $5
; R5900O0-NEXT:    move $1, $4
; R5900O0-NEXT:    mult $2, $1, $2
; R5900O0-NEXT:    jr $ra
; R5900O0-NEXT:    nop
;
; R5900O1-LABEL: Mul32:
; R5900O1:       # %bb.0:
; R5900O1-NEXT:    jr $ra
; R5900O1-NEXT:    mult $2, $4, $5
;
; R5900O2-LABEL: Mul32:
; R5900O2:       # %bb.0:
; R5900O2-NEXT:    jr $ra
; R5900O2-NEXT:    mult $2, $4, $5
  %1 = mul i32 %a, %b
  ret i32 %1
}

define i64 @Mul64(i64 signext %a, i64 signext %b) nounwind {
; R5900O0-LABEL: Mul64:
; R5900O0:       # %bb.0:
; R5900O0-NEXT:    move $1, $5
; R5900O0-NEXT:    sll $3, $1, 0
; R5900O0-NEXT:    move $1, $4
; R5900O0-NEXT:    sll $2, $1, 0
; R5900O0-NEXT:    multu $1, $2, $3
; R5900O0-NEXT:    dsll $1, $1, 32
; R5900O0-NEXT:    dsrl $1, $1, 32
; R5900O0-NEXT:    mfhi $6
; R5900O0-NEXT:    addiu $7, $zero, 0
; R5900O0-NEXT:    mtlo $6
; R5900O0-NEXT:    mthi $7
; R5900O0-NEXT:    dsrl $5, $5, 32
; R5900O0-NEXT:    # kill: def $a1 killed $a1 killed $a1_64
; R5900O0-NEXT:    sll $5, $5, 0
; R5900O0-NEXT:    madd $2, $5
; R5900O0-NEXT:    dsrl $2, $4, 32
; R5900O0-NEXT:    # kill: def $v0 killed $v0 killed $v0_64
; R5900O0-NEXT:    sll $2, $2, 0
; R5900O0-NEXT:    madd $3, $2, $3
; R5900O0-NEXT:    # implicit-def: $v0_64
; R5900O0-NEXT:    move $2, $3
; R5900O0-NEXT:    dsll $2, $2, 32
; R5900O0-NEXT:    or $2, $1, $2
; R5900O0-NEXT:    jr $ra
; R5900O0-NEXT:    nop
;
; R5900O1-LABEL: Mul64:
; R5900O1:       # %bb.0:
; R5900O1-NEXT:    sll $1, $5, 0
; R5900O1-NEXT:    sll $2, $4, 0
; R5900O1-NEXT:    multu $3, $2, $1
; R5900O1-NEXT:    mfhi $6
; R5900O1-NEXT:    dsrl $5, $5, 32
; R5900O1-NEXT:    sll $5, $5, 0
; R5900O1-NEXT:    addiu $7, $zero, 0
; R5900O1-NEXT:    mtlo $6
; R5900O1-NEXT:    mthi $7
; R5900O1-NEXT:    madd $2, $5
; R5900O1-NEXT:    dsrl $2, $4, 32
; R5900O1-NEXT:    sll $2, $2, 0
; R5900O1-NEXT:    madd $1, $2, $1
; R5900O1-NEXT:    dsll $2, $3, 32
; R5900O1-NEXT:    dsrl $2, $2, 32
; R5900O1-NEXT:    dsll $1, $1, 32
; R5900O1-NEXT:    jr $ra
; R5900O1-NEXT:    or $2, $2, $1
;
; R5900O2-LABEL: Mul64:
; R5900O2:       # %bb.0:
; R5900O2-NEXT:    sll $1, $5, 0
; R5900O2-NEXT:    sll $2, $4, 0
; R5900O2-NEXT:    multu $3, $2, $1
; R5900O2-NEXT:    mfhi $6
; R5900O2-NEXT:    dsrl $5, $5, 32
; R5900O2-NEXT:    sll $5, $5, 0
; R5900O2-NEXT:    addiu $7, $zero, 0
; R5900O2-NEXT:    mtlo $6
; R5900O2-NEXT:    mthi $7
; R5900O2-NEXT:    madd $2, $5
; R5900O2-NEXT:    dsrl $2, $4, 32
; R5900O2-NEXT:    sll $2, $2, 0
; R5900O2-NEXT:    madd $1, $2, $1
; R5900O2-NEXT:    dsll $2, $3, 32
; R5900O2-NEXT:    dsrl $2, $2, 32
; R5900O2-NEXT:    dsll $1, $1, 32
; R5900O2-NEXT:    jr $ra
; R5900O2-NEXT:    or $2, $2, $1
  %1 = mul i64 %a, %b
  ret i64 %1
}

define i64 @Mul64_Widen(i32 signext %a, i32 signext %b) nounwind {
; R5900O0-LABEL: Mul64_Widen:
; R5900O0:       # %bb.0:
; R5900O0-NEXT:    move $2, $5
; R5900O0-NEXT:    move $1, $4
; R5900O0-NEXT:    mult $1, $1, $2
; R5900O0-NEXT:    dsll $1, $1, 32
; R5900O0-NEXT:    dsrl $1, $1, 32
; R5900O0-NEXT:    mfhi $3
; R5900O0-NEXT:    # implicit-def: $v0_64
; R5900O0-NEXT:    move $2, $3
; R5900O0-NEXT:    dsll $2, $2, 32
; R5900O0-NEXT:    or $2, $1, $2
; R5900O0-NEXT:    jr $ra
; R5900O0-NEXT:    nop
;
; R5900O1-LABEL: Mul64_Widen:
; R5900O1:       # %bb.0:
; R5900O1-NEXT:    mult $1, $4, $5
; R5900O1-NEXT:    mfhi $2
; R5900O1-NEXT:    dsll $1, $1, 32
; R5900O1-NEXT:    dsrl $1, $1, 32
; R5900O1-NEXT:    dsll $2, $2, 32
; R5900O1-NEXT:    jr $ra
; R5900O1-NEXT:    or $2, $1, $2
;
; R5900O2-LABEL: Mul64_Widen:
; R5900O2:       # %bb.0:
; R5900O2-NEXT:    mult $1, $4, $5
; R5900O2-NEXT:    mfhi $2
; R5900O2-NEXT:    dsll $1, $1, 32
; R5900O2-NEXT:    dsrl $1, $1, 32
; R5900O2-NEXT:    dsll $2, $2, 32
; R5900O2-NEXT:    jr $ra
; R5900O2-NEXT:    or $2, $1, $2
  %conv = sext i32 %a to i64
  %conv2 = sext i32 %b to i64
  %1 = mul i64 %conv, %conv2
  ret i64 %1
}
