; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -march=mips64 -mcpu=mips3 -O2 < %s | FileCheck %s -check-prefix=MIPS3
; RUN: llc -mtriple=mips64el-ps2-elf -O2 --disable-machine-licm -mcpu=r5900 -verify-machineinstrs < %s | \
; RUN:   FileCheck %s -check-prefix=R5900

; Check that MipsDelaySlotFiller doesn't incorrectly fill out the delay slot of short loops
define i32 @MyMul(i32 %base, i32 %n) {
; MIPS3-LABEL: MyMul:
; MIPS3:       # %bb.0: # %entry
; MIPS3-NEXT:    sll $3, $5, 0
; MIPS3-NEXT:    sll $4, $4, 0
; MIPS3-NEXT:    move $2, $4
; MIPS3-NEXT:  .LBB0_1: # %loop
; MIPS3-NEXT:    # =>This Inner Loop Header: Depth=1
; MIPS3-NEXT:    addiu $3, $3, -1
; MIPS3-NEXT:    bnez $3, .LBB0_1
; MIPS3-NEXT:    addu $2, $2, $4
; MIPS3-NEXT:  # %bb.2: # %exit
; MIPS3-NEXT:    jr $ra
; MIPS3-NEXT:    nop
;
; R5900-LABEL: MyMul:
; R5900:       # %bb.0: # %entry
; R5900-NEXT:    sll $3, $5, 0
; R5900-NEXT:    sll $4, $4, 0
; R5900-NEXT:    move $2, $4
; R5900-NEXT:  .LBB0_1: # %loop
; R5900-NEXT:    # =>This Inner Loop Header: Depth=1
; R5900-NEXT:    addu $2, $2, $4
; R5900-NEXT:    addiu $3, $3, -1
; R5900-NEXT:    bnez $3, .LBB0_1
; R5900-NEXT:    nop
; R5900-NEXT:  # %bb.2: # %exit
; R5900-NEXT:    jr $ra
; R5900-NEXT:    nop
entry:
    br label %loop

loop:
    %i = phi i32 [%n, %entry], [%i.dec, %loop]
    %val = phi i32 [%base, %entry], [%val.next, %loop]
    %val.next = add i32 %val, %base
    %i.dec = sub i32 %i, 1
    %cond = icmp ugt i32 %i.dec, 0
    br i1 %cond, label %loop, label %exit

exit:
    ret i32 %val.next
}
